import { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle, ArrowLeft, Check, ChevronRight, CircleDollarSign, Clipboard,
  Eye, FileImage, Flag, Globe2, Home, Info, Link2, LockKeyhole, Mail,
  MessageSquare, Plus, QrCode, Radar, ScanLine, Shield, ShieldCheck,
  Siren, Sparkles, TrendingUp, Upload, UserRound, Users, WalletCards, Zap
} from 'lucide-react';
import { analyzePlatform, analyzeThreat, DEMOS } from './engine.js';
import FinanceHub from './FinanceHub.jsx';

const NAV = [
  ['home', Home, 'Home'], ['scan', ScanLine, 'Scan'], ['trust', ShieldCheck, 'Trust'],
  ['protect', LockKeyhole, 'Protect'], ['community', Users, 'Community'], ['emergency', Siren, 'Emergency']
];

const demoThreats = [
  { type: 'Phishing SMS', source: 'NatWest account suspended', time: '2m ago' },
  { type: 'Fake Store', source: 'bestdeals4u-discount.shop', time: '8m ago' },
  { type: 'Crypto scam', source: 'Guaranteed returns campaign', time: '14m ago' }
];

function useStoredState(key, initial) {
  const [value, setValue] = useState(() => {
    try { return JSON.parse(localStorage.getItem(key)) ?? initial; } catch { return initial; }
  });
  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]);
  return [value, setValue];
}

function Brand() {
  return <div className="brand"><span className="brand-mark"><Sparkles size={20} /></span><b>nata<span>CONNECT</span></b></div>;
}

function PageTitle({ icon: Icon, title, subtitle, tone = 'blue' }) {
  return <div className="page-title"><span className={`title-icon ${tone}`}><Icon size={22}/></span><div><h1>{title}</h1><p>{subtitle}</p></div></div>;
}

function Gauge({ value, label, color, suffix='/100' }) {
  return <div className="gauge-wrap"><div className="gauge" style={{'--value': value, '--color': color}}><div><b>{value}</b><small>{suffix}</small></div></div><span>{label}</span></div>;
}

function Shell({ page, setPage, mode, setMode, children }) {
  return <div className={`app-shell ${mode==='finance'?'finance-mode':''}`}><main><header><Brand/><span className="protected"><Check size={12}/> Local-first</span></header><div className="product-switch"><button className={mode==='security'?'active':''} onClick={()=>setMode('security')}><Shield/>Security</button><button className={mode==='finance'?'active':''} onClick={()=>setMode('finance')}><WalletCards/>Finance</button></div>{mode==='security'?children:<FinanceHub/>}</main>{mode==='security'&&<nav>{NAV.map(([id, Icon, label]) => <button key={id} className={page===id?'active':''} onClick={() => setPage(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>}</div>;
}

function Dashboard({ setPage, scanCount }) {
  return <section className="screen fade-in"><div className="hero"><span className="hero-kicker"><Zap/> PRIVATE, EXPLAINABLE FRAUD DEFENSE</span><h1>Spot the scam<br/><em>before it costs you.</em></h1><p>SentinelAI turns suspicious messages and links into clear evidence and immediate next steps, entirely on your device.</p><button onClick={()=>setPage('scan')}><Sparkles/>Run the 10-second scam demo<ChevronRight/></button><div className="privacy-row"><span><ShieldCheck/>No uploads</span><span><Radar/>12 risk models</span><span><Zap/>Instant results</span></div></div><p className="eyebrow section-label">YOUR SECURITY DASHBOARD</p><div className="panel gauges"><Gauge value={82} label="Security Score" color="#20e87a"/><Gauge value={34} label="Financial Risk" color="#ff335f"/><Gauge value={58} label="ID Exposure" color="#ffd51e"/></div><div className="mini-stats"><div><ShieldCheck/><b>{13 + scanCount}</b><span>Threats Checked</span></div><div><Radar/><b>{48 + scanCount}</b><span>Total Scans</span></div><div><Eye/><b>3</b><span>Active Alerts</span></div></div><p className="eyebrow section-label">QUICK ACTIONS</p><div className="quick-grid"><button className="quick blue" onClick={()=>setPage('scan')}><ScanLine/><div><b>Scan Content</b><span>Explain a threat</span></div><ChevronRight/></button><button className="quick green" onClick={()=>setPage('trust')}><TrendingUp/><div><b>Trust Score</b><span>Inspect a platform</span></div><ChevronRight/></button><button className="quick purple" onClick={()=>setPage('protect')}><LockKeyhole/><div><b>Protect</b><span>Set safety rules</span></div><ChevronRight/></button><button className="quick red" onClick={()=>setPage('emergency')}><AlertTriangle/><div><b>Emergency</b><span>Start recovery</span></div><ChevronRight/></button></div><div className="section-heading"><p className="eyebrow">COMMUNITY SIGNALS</p><button onClick={()=>setPage('community')}>View all <ChevronRight size={13}/></button></div><div className="feed">{demoThreats.slice(0,2).map(t=><div key={t.source}><i/><p><b>{t.type}</b><span>{t.source}</span></p><time>{t.time}</time></div>)}</div></section>;
}

const scanTypes = [
  ['url', Link2, 'URL'], ['sms', MessageSquare, 'SMS'], ['email', Mail, 'Email'],
  ['qr', QrCode, 'QR Code'], ['image', FileImage, 'Screenshot'], ['chat', MessageSquare, 'Chat / WhatsApp']
];

function Scanner({ onScan }) {
  const [type,setType]=useState('url'); const [input,setInput]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [history,setHistory]=useStoredState('sentinel-history',[]);
  const scan=()=>{ if(!input.trim()) return; setLoading(true); setResult(null); setTimeout(()=>{const next=analyzeThreat(input,type);setResult(next);setHistory([{id:Date.now(),type,preview:input.slice(0,52),score:next.score,verdict:next.verdict},...history].slice(0,5));setLoading(false);onScan();},650); };
  const loadDemo=(value)=>{setInput(value);setResult(null)};
  return <section className="screen fade-in"><PageTitle icon={ScanLine} title="Explainable Threat Scanner" subtitle="Private on-device analysis for links and messages"/><div className="demo-banner"><div><span>JUDGE DEMO</span><b>Can SentinelAI catch a bank impersonation scam?</b></div><button onClick={()=>loadDemo(DEMOS.bank)}><Zap/>Load demo</button></div><div className="type-grid">{scanTypes.map(([id,Icon,label])=><button key={id} className={type===id?'selected':''} onClick={()=>{setType(id);setResult(null)}} aria-label={`Scan ${label}`}><Icon/><span>{label}</span></button>)}</div><div className="panel form-panel">{type==='image'||type==='qr'?<button className="upload" onClick={()=>loadDemo('URGENT payment request detected in screenshot. Send crypto to unlock your account.')}><Upload/><b>Simulate a {type==='qr'?'QR code':'screenshot'} scan</b><span>Runs locally with demo extracted text</span></button>:<><label>{type==='url'?'URL OR DOMAIN':type==='sms'?'SMS MESSAGE':type==='email'?'EMAIL CONTENT':'CHAT CONTENT'}</label><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={`Paste suspicious ${type} content here...`} aria-label="Content to analyze"/></>}<div className="demos"><span>One-tap scenarios:</span><button onClick={()=>loadDemo(DEMOS.bank)}>Bank impersonation</button><button onClick={()=>loadDemo(DEMOS.investment)}>Investment scam</button><button onClick={()=>loadDemo(DEMOS.safe)}>Safe link</button></div><button className="primary" onClick={scan} disabled={!input||loading}>{loading?<><span className="spinner"/>Running 12 local risk models...</>:<><Sparkles/>Explain This Threat</>}</button><p className="local-note"><ShieldCheck/>Content never leaves this device</p></div>{result&&<ThreatResult result={result}/>} {history.length>0&&<div className="panel history"><div className="section-heading"><p className="eyebrow">RECENT PRIVATE SCANS</p><button onClick={()=>setHistory([])}>Clear</button></div>{history.map(h=><button key={h.id} onClick={()=>{setInput(h.preview);setResult(null)}}><span className={`risk-dot ${h.score>=45?'hot':''}`}/><p><b>{h.verdict}</b><span>{h.preview}</span></p><strong>{h.score}</strong></button>)}</div>}<div className="panel model-card"><Info/><div><b>How it works</b><span>SentinelAI combines transparent behavioral rules, language patterns, and domain structure. It does not claim certainty or upload your content.</span></div></div></section>;
}

function ThreatResult({result}) { const risky=result.score>=45; const copy=()=>navigator.clipboard?.writeText(`${result.verdict}: ${result.score}/100 risk. ${result.summary}`); return <div className={`analysis-card ${result.level}`}><div className="verdict-head"><div className="score-ring" style={{'--score':result.score}}><b>{result.score}</b><small>RISK</small></div><div><span className="verdict-label">SENTINEL VERDICT</span><h2>{result.verdict}</h2><p>{result.summary}</p></div><button onClick={copy} title="Copy result"><Clipboard/></button></div>{result.signals.length>0&&<div className="evidence"><p className="eyebrow">WHY THIS WAS FLAGGED</p>{result.signals.map(s=><div key={s.id}><span className={`severity ${s.level}`}>{s.level}</span><p><b>{s.category}</b><small>{s.evidence}</small></p><strong>+{s.weight}</strong></div>)}</div>}<div className="actions"><p className="eyebrow">WHAT TO DO NEXT</p>{result.actions.map((a,i)=><div key={a}><i>{i+1}</i>{a}</div>)}</div><div className={`confidence ${risky?'warn':''}`}><Info/>{risky?'Treat this as suspicious until verified independently.':'Low risk is not a guarantee. Stay alert for unexpected requests.'}</div></div> }

function Trust() {
  const [url,setUrl]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState(null);
  const check=()=>{if(!url)return;setLoading(true);setTimeout(()=>{setResult(analyzePlatform(url));setLoading(false)},650)};
  return <section className="screen fade-in"><PageTitle icon={ShieldCheck} title="Platform Trust Lab" subtitle="Inspect broker and investment claims before paying" tone="green"/><div className="panel form-panel"><label>BROKER URL OR PLATFORM NAME</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="company.com or platform name"/><div className="demos"><span>Compare scenarios:</span><button onClick={()=>setUrl('crypto-double-returns.top/invest')}>Suspicious broker</button><button onClick={()=>setUrl('coinbase.com')}>Known domain</button></div><button className="primary" onClick={check} disabled={!url||loading}>{loading?<><span className="spinner"/>Inspecting domain patterns...</>:<><ShieldCheck/>Generate Trust Report</>}</button></div>{result&&<><div className="panel trust-gauges"><p className="eyebrow">EXPLAINABLE TRUST ANALYSIS</p><div><Gauge value={result.trust} label="Trust Score" color={result.safe?'#20e87a':'#ff335f'}/><Gauge value={result.regulation} label="Verification" color={result.safe?'#20e87a':'#ffd51e'}/><Gauge value={result.domainRisk} label="Domain Risk" color={result.safe?'#20e87a':'#ff335f'}/></div></div><div className={`panel indicators ${result.safe?'positive':''}`}><p className="eyebrow">{result.safe?'POSITIVE DOMAIN SIGNALS':'RISK INDICATORS'}</p>{result.indicators.length?result.indicators.map(x=><div key={x.id}>{result.safe?<Check/>:<AlertTriangle/>}<span><b>{x.category}</b><small>{x.evidence}</small></span></div>):<div><Check/>No high-risk structural patterns detected</div>}</div><div className="panel model-card"><Info/><div><b>Scope of this report</b><span>This is an on-device structural assessment, not a regulatory lookup. Always verify licences on the regulator's official website.</span></div></div></>}</section>;
}

const initialRules=[['Warn for payments above €500','transaction'],['Warn for crypto websites','url'],['Warn for new domains (< 30 days)','domain'],['Warn for foreign transactions','transaction'],['Warn for gambling sites','url']];
function Protect() {
  const [tab,setTab]=useState('personal'); const [rules,setRules]=useStoredState('sentinel-rules',initialRules.map((x,i)=>({...x,id:i,on:i!==3}))); const [identity,setIdentity]=useState(''); const [checked,setChecked]=useState(false);
  const toggle=id=>setRules(rules.map(r=>r.id===id?{...r,on:!r.on}:r));
  return <section className="screen fade-in"><PageTitle icon={LockKeyhole} title="Protect" subtitle="Identity Shield · Rules Engine · Transaction Simulator" tone="purple"/><div className="tabs">{['identity','personal','transaction'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x==='identity'?<UserRound/>:x==='personal'?<Shield/>:<WalletCards/>}{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{tab==='personal'&&<div className="panel rules"><div className="section-heading"><div><h3>Your Security Rules</h3><span>AI applies these automatically on every scan</span></div><button className="icon-btn"><Plus/></button></div>{rules.map(r=><div className="rule" key={r.id}><button className={`switch ${r.on?'on':''}`} onClick={()=>toggle(r.id)}><i/></button><b>{r[0]}</b><span>{r[1]}</span></div>)}</div>}{tab==='identity'&&<div className="panel form-panel"><h3>Check Your Digital Exposure</h3><p className="muted">Search locally for common breach-risk patterns.</p><input value={identity} onChange={e=>setIdentity(e.target.value)} placeholder="your@email.com"/><button className="primary" onClick={()=>setChecked(true)} disabled={!identity}><Radar/>Check Exposure</button>{checked&&<div className="inline-note"><ShieldCheck/>No live breach lookup is performed. Enable an API later for real breach data.</div>}</div>}{tab==='transaction'&&<TransactionSim/>}</section>;
}

function TransactionSim(){const [amount,setAmount]=useState('');const [foreign,setForeign]=useState(false);const risk=(+amount>500?35:5)+(foreign?35:0);return <div className="panel form-panel"><h3>Transaction Simulator</h3><label>PAYMENT AMOUNT (€)</label><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/><button className={`check-row ${foreign?'checked':''}`} onClick={()=>setForeign(!foreign)}><i>{foreign&&<Check/>}</i>Foreign transaction</button>{amount&&<div className={`inline-note ${risk>40?'warn':''}`}>{risk>40?<AlertTriangle/>:<ShieldCheck/>}{risk>40?'This transaction matches active warning rules.':'No active rule was triggered.'}</div>}</div>}

function Community(){const [tab,setTab]=useState('overview');const [reports,setReports]=useStoredState('sentinel-reports',[]);const [form,setForm]=useState({type:'Phishing',source:'',desc:''});const submit=()=>{if(!form.source)return;setReports([{...form,id:Date.now()},...reports]);setForm({...form,source:'',desc:''});setTab('reports')};return <section className="screen fade-in"><PageTitle icon={Users} title="Community Intel" subtitle="Crowdsourced threat intelligence · Live scam database" tone="purple"/><div className="tabs three"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Globe2/>Overview</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}><Flag/>Reports</button><button className={tab==='submit'?'active':''} onClick={()=>setTab('submit')}><Plus/>Submit</button></div>{tab==='overview'&&<><div className="community-stats"><div><Flag/><p><b>12,847</b><span>Threats Reported</span></p><small>+124 today</small></div><div><Users/><p><b>8,291</b><span>Active Members</span></p><small>+43 today</small></div><div><TrendingUp/><p><b>€4.2M</b><span>Scams Prevented</span></p><small>Saved this month</small></div></div><div className="panel hotspots"><p className="eyebrow">GLOBAL SCAM HOTSPOTS</p>{[['United Kingdom',3241,100],['United States',2876,82],['India',1943,59],['Nigeria',1621,48],['Germany',987,30]].map(x=><div key={x[0]}><span>{x[0]}</span><i><em style={{width:x[2]+'%'}}/></i><small>{x[1].toLocaleString()}</small></div>)}</div></>}{tab==='reports'&&<div className="feed reports">{[...reports,...demoThreats].map((r,i)=><div key={r.id||i}><i/><p><b>{r.type}</b><span>{r.source}</span></p><time>{r.id?'just now':r.time}</time></div>)}</div>}{tab==='submit'&&<div className="panel form-panel"><h3>Report a Scam</h3><p className="muted">Help protect others by submitting threat intelligence.</p><label>SCAM TYPE</label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Phishing</option><option>Investment scam</option><option>Fake store</option><option>Impersonation</option></select><label>URL / SENDER / MESSAGE</label><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="https://scam-site.xyz or +44..."/><label>DESCRIPTION</label><textarea value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} placeholder="Describe what happened..."/><button className="primary" onClick={submit} disabled={!form.source}><Flag/>Submit Report</button></div>}</section>}

function Emergency(){const [flow,setFlow]=useState(false);const [step,setStep]=useState(1);const [loss,setLoss]=useState('');if(flow)return <section className="screen fade-in"><button className="back" onClick={()=>setFlow(false)}><ArrowLeft/>Back</button><PageTitle icon={Siren} title="Recovery Plan" subtitle={`Step ${step} of 3 · Act quickly and keep evidence`} tone="red"/><div className="panel recovery"><div className="stepper">{[1,2,3].map(n=><i key={n} className={step>=n?'active':''}>{step>n?<Check/>:n}</i>)}</div>{step===1&&<><h2>Stop the money movement</h2><p>Contact your bank or card provider immediately. Ask them to freeze the payment and secure your account.</p><label>ESTIMATED AMOUNT LOST (€)</label><input value={loss} onChange={e=>setLoss(e.target.value)} placeholder="0"/></>}{step===2&&<><h2>Secure your accounts</h2>{['Change banking and email passwords','Enable two-factor authentication','Sign out unknown devices'].map(x=><div className="task" key={x}><Check/>{x}</div>)}</>}{step===3&&<><h2>Save evidence and report</h2><p>Keep screenshots, transaction IDs, phone numbers and messages. Report the incident to your national fraud service and police.</p><div className="inline-note warn"><Flag/>Your recovery checklist is ready.</div></>}<button className="primary emergency-btn" onClick={()=>setStep(Math.min(3,step+1))}>{step===3?'Plan Complete':'Continue'}<ChevronRight/></button></div></section>;return <section className="screen fade-in"><PageTitle icon={Siren} title="Emergency Mode" subtitle="Immediate fraud response. We'll guide you step by step." tone="red"/><button className="panic" onClick={()=>setFlow(true)}><span><AlertTriangle/></span><b>I THINK I WAS SCAMMED</b><small>Tap to start emergency recovery flow</small></button><div className="panel contacts"><p className="eyebrow">EMERGENCY CONTACTS</p><a href="tel:03001232040"><Flag/>Action Fraud (UK)<b>0300 123 2040</b></a><a href="tel:08001116768"><CircleDollarSign/>FCA (Financial Scams)<b>0800 111 6768</b></a><a href="tel:101"><Siren/>Cyber Crime Reporting<b>101 (Police)</b></a></div></section>}

export default function App(){const [page,setPage]=useState('home');const [mode,setMode]=useStoredState('sentinel-product',window.location.hash==='#finance'?'finance':'security');const [scanCount,setScanCount]=useStoredState('sentinel-scans',0);useEffect(()=>{if(window.location.hash==='#finance'||window.location.hash==='#security')setMode(window.location.hash.slice(1))},[]);const switchMode=next=>{setMode(next);window.history.replaceState(null,'',next==='finance'?'#finance':'#security')};const content=useMemo(()=>({home:<Dashboard setPage={setPage} scanCount={scanCount}/>,scan:<Scanner onScan={()=>setScanCount(scanCount+1)}/>,trust:<Trust/>,protect:<Protect/>,community:<Community/>,emergency:<Emergency/>}),[page,scanCount]);return <Shell page={page} setPage={setPage} mode={mode} setMode={switchMode}>{content[page]}</Shell>}
